#!/bin/bash

echo "════════════════════════════════════════════════════════════"
echo "           PLATYPUS - CHEATSHEET"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "📌 TÄGLICH:"
echo "  ./scripts/daily-start.sh          → Full status + shortcuts"
echo "  ./scripts/status-all.sh           → Project + Orders Overview"
echo ""
echo "📦 ORDERS:"
echo "  ./scripts/orders-menu.sh          → Full Order Menu"
echo "  ./scripts/quick-order.sh          → Schnelle Testorder"
echo "  ./scripts/quick-paid.sh           → Letzte Order als paid"
echo "  ./scripts/test-flow.sh            → Kompletter Test (Order → Paid)"
echo ""
echo "🛠️  PROJECT:"
echo "  ./scripts/project.sh check        → Health Check"
echo "  ./scripts/project.sh dev          → Dev Server"
echo "  ./scripts/project.sh urls         → Wichtige Links"
echo ""
echo "📤 GIT:"
echo "  ./scripts/git/commit-all.sh       → Alles committen + pushen"
echo ""
echo "════════════════════════════════════════════════════════════"
