#!/bin/bash
echo "════════════════════════════════════════════════════════════"
echo " PLATYPUS Project Info"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Branch: $(git branch --show-current)"
echo "Letzter Commit: $(git log -1 --oneline)"
echo ""
echo "Wichtige Dateien:"
[ -f app/components/Viewer/Viewer.tsx ] && echo "  ✅ Viewer"
[ -f app/cart/page.tsx ] && echo "  ✅ Cart"
[ -f scripts/deploy.sh ] && echo "  ✅ Deploy Script"
echo ""
echo "════════════════════════════════════════════════════════════"
