#!/bin/bash
echo "════════════════════════════════════════════════════════════"
echo " Vercel Git Integration einrichten"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Schritte:"
echo ""
echo "1. Gehe auf: https://vercel.com/dashboard"
echo "2. Wähle dein Projekt: platypus-shirt-shop"
echo "3. Gehe zu: Settings → Git"
echo "4. Klicke auf 'Connect Git Repository'"
echo "5. Wähle dein GitHub Repository aus"
echo "6. Wähle den Branch 'main'"
echo ""
echo "Danach:"
echo "- Jeder 'git push' triggert automatisch ein neues Deployment"
echo "- Pull Requests erzeugen Preview Deployments"
echo ""
echo "════════════════════════════════════════════════════════════"
