#!/bin/bash
echo "════════════════════════════════════════════════════════════"
echo " PLATYPUS Status"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Branch: $(git branch --show-current)"
echo "Letzter Commit: $(git log -1 --oneline)"
echo ""
echo "Deploy Scripts:"
ls -1 scripts/*.sh 2>/dev/null | wc -l | xargs echo "  Anzahl:"
echo ""
echo "════════════════════════════════════════════════════════════"
