#!/bin/bash

echo "════════════════════════════════════════════════════════════"
echo "           PLATYPUS - EIGENE TOOLS ÜBERSICHT"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "📦 ORDER SYSTEM"
echo "  orders-menu.sh          → Vollständiges Order Menü"
echo "  dashboard.sh            → Schnelle Übersicht + Umsatz"
echo "  quick-order.sh          → Schnelle Testorder anlegen"
echo "  quick-paid.sh           → Letzte Order als bezahlt markieren"
echo "  test-flow.sh            → Kompletter Test (Order → Paid)"
echo "  status-all.sh           → Project + Orders auf einen Blick"
echo ""
echo "🛠️  PROJECT & DEV"
echo "  project.sh              → Zentrales Control Script"
echo "  daily-start.sh          → Täglicher Start mit Status"
echo "  cheatsheet.sh           → Wichtige Befehle"
echo "  p                       → Kurzbefehle (p o, p d, p s ...)"
echo ""
echo "📤 GIT & BACKUP"
echo "  git/save-work.sh        → Schnell committen + pushen"
echo "  git/overview.sh         → Git Status schön anzeigen"
echo "  backup-scripts.sh       → Alle Skripte sichern"
echo ""
echo "════════════════════════════════════════════════════════════"
