#!/bin/bash
echo "════════════════════════════════════════════════════════════"
echo " Vercel Environment Variables (CLI)"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Verfügbare Befehle:"
echo ""
echo "  vercel env ls                    → Alle Variablen anzeigen"
echo "  vercel env add NAME              → Neue Variable hinzufügen"
echo "  vercel env pull .env.local       → Variablen lokal herunterladen"
echo "  vercel env rm NAME               → Variable löschen"
echo ""
echo "Beispiele:"
echo "  vercel env add STRIPE_SECRET_KEY"
echo "  vercel env add NEXT_PUBLIC_SITE_URL"
echo ""
echo "════════════════════════════════════════════════════════════"
