#!/bin/bash
echo "════════════════════════════════════════════════════════════"
echo " Vercel Build Hooks (Deploy Hooks)"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Build Hooks erlauben es, einen neuen Deploy per URL auszulösen."
echo ""
echo "So richtest du einen Hook ein:"
echo ""
echo "1. Gehe auf vercel.com → Dein Projekt"
echo "2. Settings → Deploy Hooks"
echo "3. Neuen Hook erstellen (z.B. 'Main Branch')"
echo "4. Die generierte URL kopieren"
echo ""
echo "Hook manuell triggern:"
echo '  curl -X POST "https://api.vercel.com/v1/integrations/deploy/..."'
echo ""
echo "Tipp: Gut für externe Trigger (z.B. von einem anderen System)"
echo ""
echo "════════════════════════════════════════════════════════════"
