#!/bin/bash
echo "════════════════════════════════════════════════════════════"
echo " PLATYPUS Environment Variables"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "  ./scripts/env-add.sh     → Variable hinzufügen"
echo "  ./scripts/env-list.sh    → Alle Variablen anzeigen"
echo "  ./scripts/env-pull.sh    → .env.local herunterladen"
echo ""
echo "════════════════════════════════════════════════════════════"
