#!/bin/bash
echo "════════════════════════════════════════════════════════════"
echo "           PLATYPUS - AKTUELLER LAGEBERICHT"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "📦 Git Status:"
git status --short
echo ""
echo "Letzte 5 Commits:"
git log --oneline -5
echo ""
echo "🛠️ Bash Tooling:"
[ -f scripts/p ] && echo "  ✅ scripts/p vorhanden" || echo "  ❌ scripts/p fehlt"
[ -f scripts/deploy-now.sh ] && echo "  ✅ deploy-now.sh vorhanden" || echo "  ❌ deploy-now.sh fehlt"
echo ""
echo "🖥️ Wichtige Dateien:"
[ -f app/layout.tsx ] && echo "  ✅ layout.tsx" || echo "  ❌ layout.tsx fehlt"
[ -f app/components/Viewer/Viewer.tsx ] && echo "  ✅ Viewer.tsx" || echo "  ❌ Viewer.tsx fehlt"
[ -f app/cart/page.tsx ] && echo "  ✅ cart/page.tsx" || echo "  ❌ cart/page.tsx fehlt"
echo ""
echo "════════════════════════════════════════════════════════════"
