#!/bin/bash
echo "════════════════════════════════════════════════════════════"
echo "           PLATYPUS ORDERS - VERFÜGBARE SKRIPTE"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "  orders-list.sh          → Alle Orders anzeigen"
echo "  orders-pending.sh       → Nur pending Orders"
echo "  orders-recent.sh        → Letzte 10 Orders"
echo "  orders-by-status.sh     → Orders nach Status filtern"
echo "  orders-search.sh        → Orders suchen (Name/Email)"
echo "  orders-show.sh          → Details einer Order (ID)"
echo "  orders-add.sh           → Neue Order anlegen"
echo "  orders-change-status.sh → Status einer Order ändern"
echo "  orders-update-status.sh → Schnell auf 'paid' setzen"
echo "  orders-delete.sh        → Order löschen"
echo "  orders-stats.sh         → Statistik & Umsatz"
echo "  orders-export-csv.sh    → Export als CSV"
echo "  orders-to-json.sh       → Export als JSON"
echo "  orders-backup.sh        → Datenbank Backup"
echo "  simulate-stripe-webhook.sh → Webhook Simulation"
echo "  orders-seed.sh          → Testdaten generieren"
echo "  orders-reset.sh         → Datenbank zurücksetzen"
echo "  orders-menu.sh          → Interaktives Menü"
echo ""
echo "════════════════════════════════════════════════════════════"
