#!/bin/bash
echo "════════════════════════════════════════════════════════════"
echo " PLATYPUS Performance Optimierung"
echo "════════════════════════════════════════════════════════════"
echo ""

echo "1. Bilder optimieren → next/image verwenden"
echo "2. Fonts optimieren → next/font verwenden"
echo "3. Bundle analysieren:"
echo "   npm run build && npx @next/bundle-analyzer"
echo ""
echo "4. Edge Runtime nutzen wo sinnvoll (Middleware, API Routes)"
echo "5. Statische Seiten wo möglich (generateStaticParams)"
echo "6. Caching Header setzen"
echo ""
echo "Schnell-Check:"
echo "  npm run build"
echo ""
echo "════════════════════════════════════════════════════════════"
